name: deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: ログレベル
        default: warning

env:
  FUNCTION_ENV: ${{ secrets.FUNCTION_ENV }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_SA_PROJECT_ID: ${{ secrets.GCP_SA_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew shadowJar
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_SA_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy To Google Functions
        run: |
          echo $FUNCTION_ENV | base64 -d > env.yaml
          gcloud functions deploy cio-feeder \
            --project $GCP_SA_PROJECT_ID \
            --quiet \
            --entry-point=org.springframework.cloud.function.adapter.gcp.GcfJarLauncher \
            --trigger-topic=favorite \
            --env-vars-file=env.yaml \
            --runtime=java11 \
            --region asia-northeast1 \
            --source=build/libs \
            --memory=1024MB \
            --timeout=300
